services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    restart: always

  argocd-server:
    image: argoproj/argocd:v2.6.15
    container_name: argocd-server
    command: ["argocd-server", "--insecure"]
    ports:
      - "8081:8080"
    volumes:
      - argocd-data:/data
    restart: always

  trivy:
    image: aquasec/trivy:latest
    container_name: trivy
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  validator:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: k8s-validator
    working_dir: /app
    command: ["--manifest", "k8s/deployment.yaml"]
    volumes:
      - ./k8s:/app/k8s
      - ./validation-framework:/app/validation-framework
    restart: no

volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  argocd-data: