version: "3.8"
 
services:
  jenkins:
    build:
      context: .
      dockerfile: docker/Jenkins.Dockerfile
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      DOCKER_USER: ${DOCKER_USER}
      DOCKER_PASS: ${DOCKER_PASS}
      SONAR_TOKEN: ${SONAR_TOKEN}
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
 
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    restart: always
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - "9000:9000"
    depends_on:
      - db
 
  db:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - postgres_data:/var/lib/postgresql/data
 
  argocd:
    image: argoproj/argocd
    container_name: argocd
    restart: always
    ports:
      - "8081:8080"
 
volumes:
  jenkins_home:
  postgres_data: