version: "3.9"
 
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped
 
  sonarqube:
    image: sonarqube:10.5-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    restart: unless-stopped
 
  argocd-server:
    image: argoproj/argocd:v2.10.7
    container_name: argocd-server
    ports:
      - "8081:8080"
    command: ["argocd-server", "--insecure"]
    volumes:
      - argocd-data:/var/lib/argocd
    depends_on:
      - repo-server
    restart: unless-stopped
 
  repo-server:
    image: argoproj/argocd-repo-server:v2.10.7
    container_name: argocd-repo-server
    volumes:
      - argocd-data:/var/lib/argocd
    restart: unless-stopped
 
  trivy:
    image: aquasec/trivy:latest
    container_name: trivy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./trivy-cache:/root/.cache/
    entrypoint: tail -f /dev/null # Keep container running
    restart: unless-stopped
 
volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  argocd-data: