replicaCount: 1

image:
  repository: your-dockerhub-username/devsecops-validator
  tag: latest  # This will be updated automatically by Jenkins
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

securityContext:
  runAsNonRoot: true
  readOnlyRootFilesystem: true

containerSecurityContext:
  runAsNonRoot: true
  readOnlyRootFilesystem: true

livenessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 10
  periodSeconds: 5

readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 5

nodeSelector: {}

tolerations: []

affinity: {}
