apiVersion: apps/v1
kind: Deployment
metadata:
 name: devsecops-app
spec:
 replicas: 2
 selector:
  matchLabels:
    app: devsecops-app
  template:
   metadata:
    matchLabels: 
     app: devsecops-app
  spec:
    containers:
     - name: devsecops-container
       image: your-docker-username/devsecops-app:latest
       securityContext:
        runAsNonRoot: true