apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validator-demo
  template:
    metadata:
      labels:
        app: validator-demo
    spec:
      containers:
        - name: validator-demo-container
          image: nginx:latest
          ports:
            - containerPort: 80
          securityContext:
            runAsNonRoot: true
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
 