apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devsecops-project
  namespace: argocd
spec:
  description: Project for DevSecOps Kubernetes Deployment Validation Framework
  sourceRepos:
    - 'https://github.com/AryanShukla29/DevSecOps-k8s-framework.git'
  destinations:
    - namespace: default
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
