name: CI Pipeline

on:
  push:
   branches: [main]

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run Python Lint
      run: pip install pylint && pylint validate_manifest.py

    - name: Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
       scan-type: "fs"
       severity: 'HIGH'

    - name: Kubernetes Manifest Validation
      run: python3 validate_manifest.pyk8s/deployment.yaml